"""add phone to users

Revision ID: 185e4d362a81
Revises: 580727017d23
Create Date: 2026-09-29 17:41:27.988687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185e4d362a81'
down_revision = '580727017d23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
