"""add phone to users

Revision ID: 2eaf395a08e5
Revises: 185e4d362a81
Create Date: 2026-09-29 17:58:29.505643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eaf395a08e5'
down_revision = '185e4d362a81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
