"""add user_positions

Revision ID: 6862a8d269f3
Revises: a021f4275673
Create Date: 2026-09-29 12:25:48.482659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6862a8d269f3'
down_revision = 'a021f4275673'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_positions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'position_id')
    )
    op.drop_constraint(op.f('users_position_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'position_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_position_id_fkey'), 'users', 'positions', ['position_id'], ['id'], ondelete='SET NULL')
    op.drop_table('user_positions')
    # ### end Alembic commands ###
