"""add user_positions

Revision ID: 872272390752
Revises: 6862a8d269f3
Create Date: 2026-09-29 12:26:10.521560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872272390752'
down_revision = '6862a8d269f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
